image: alpine/edge
packages:
  - rust
  - cargo
sources:
  - https://git.sr.ht/~zethra/freedesktop_entry_parser
tasks:
  - build: |
      cd freedesktop_entry_parser
      cargo build --all-features
  - test: |
      cd freedesktop_entry_parser
      cargo test --all-features
